name: Release Helm Chart
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
